### ISSUE TITLE
Unknown column 'duration' in 'where clause'

### ISSUE THREAD

**Issue by benks-io** [nextcloud/polls#1792]
## What is going wrong? What did you observe?
After trying to update to Polls on a NC 20.0.0, NC was not available anymore.
After disabling polls via occ and updating NC to 20.0.2, installing the Polls App in the admin web interface shows the error message:

`An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'duration' in 'where clause'`

**Add a screenshot of the misbehavior**

![image](https://user-images.githubusercontent.com/57667105/123768076-4eadbd80-d8c8-11eb-8f64-aca7d4d002ee.png)

What should be done to fix the Database Column?

## Information about your polls installation
**Polls version:** 2.0.4

**Fresh installation or update from a prior version (from which one)?**
- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: unkown

**How did you install this version?(Appstore or describe installation)**
Booth fail:
- [x] Installed from the appstore
- [x] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 20.0.0 then 20.0.2

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

**Comment by dartcafe** [comment]
Seems like you are updating from an older version. Should be fixed with https://github.com/nextcloud/polls/pull/1781 and 2.0.5. Will come shortly.

**Comment by caemor** [comment]
Got the same issue when updating my instance today. Now I was stuck in maintenance mode and after disabling it, the webpage was still stuck in the update app mode.
Removing the apps/pools folder solved the issue for me (this stopped it trying to update the polls app, but also removed everything from it (besides the stuff stored in the database))

**Comment by dartcafe** [comment]
2.0.5 was released today here on github. Appstore release can be delayed.

**Comment by dartcafe** [comment]
Feedback is welcome, if the installation worked.

**Comment by TheLux83** [comment]
Since version 2.0.5 is released in the app store, I've tried to reinstall polls.
I've also deleted the whole custom_apps/polls folder, but I still get the error "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'duration' in 'where clause'"
I'm using Nextcloud 21.0.3

**Comment by dartcafe** [comment]
>  I've also deleted the whole custom_apps/polls folder, but I still get the error

In this case, it is impossible that the error occurs, because the executed file is deleted, unless Polls is installed in another directory (i.e. `./apps/polls`).

**Comment by TheLux83** [comment]
> > I've also deleted the whole custom_apps/polls folder, but I still get the error
> 
> In this case, it is impossible that the error occurs, because the executed file is deleted, unless Polls is installed in another directory (i.e. `./apps/polls`).

I've searched the whole data folder for 'polls' but it only was in custom_apps.
Maybe it is of importance, that I'm using the docker image of Nextclour?
Or can I somehow update the database? Normally Nexrxloud asks if it would like to update the database. But maybe it is required here?

**Comment by dartcafe** [comment]
Look in the apps folder of the Nextcloud installation, not in the data folder. I know the docker containers handle the apps dir differently. 

But if the error stays, there seems to be an polls installation of 2.0.4 anywhere. In 2.0.5 this error should not occur anymore, because the existance of the duration column is checked before the repair step.

**Comment by TheLux83** [comment]
I found the error!

For unknown reasons, my database still had values saved from an (very) old installation

|appid |configkey |configvalue |
|---|---|---|
|polls |enabled |no |
|polls |installed_version |1.4.3 |
|polls |types | |

I've deleted these columns, deleted the polls folder from my custom_apps and now I was able to completely download and install polls.

Thanks for hinting me in the right direction :-)

**Comment by benks-io** [comment]
@TheLux83 What exactly did you delete in which table?

**Comment by TheLux83** [comment]
> @TheLux83 What exactly did you delete in which table?

The values are in the table: `oc_appconfig` in your nextcloud database and I've deleted all three values which I have shown above.
It seems that a previous installation wasn't deleted completely and had zombie values stored in my database.

**Comment by benks-io** [comment]
Deleting the three **rows** worked for me.

**Comment by dartcafe** [comment]
Thanks for reporting your fix. Wasn't aware of this table. 👍
