### ISSUE TITLE
cannot share poll (only share option)

### ISSUE THREAD

**Issue by cimbi** [nextcloud/polls#532]
### What is going wrong?

Since update to 0.10.0 I cannot share the polls with other users via Only shared option. There is simply no widget.
![poll_bug](https://user-images.githubusercontent.com/15217634/53339973-1c5eb080-3908-11e9-94b2-612301c8d7a2.png)

**Comment by brtptrs** [comment]
I can confirm this problem

**Comment by brtptrs** [comment]
![z_screenshot_20190225_003](https://user-images.githubusercontent.com/8102905/53351505-b0894180-3921-11e9-9b76-10a90da16cf4.png)

Firefox shows these errors when "apps/polls/new" is called.

**Comment by gschbro** [comment]
Confirmed, same here :-(

**Comment by horstvogel** [comment]
confirmed, same Problem on Nextcloud 15.04 with 0.10.0

**Comment by dartcafe** [comment]
Ther seems to be a problem in the build process. I will check that. The compiled js in the package differs from my local compilation.

**Comment by dieter-wilhelm** [comment]
I've the same problem on NextCloud 15.0.5

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/releases/tag/v0.10.1 should fix that. Appstore release will come up soon.
@v1r0x If you have time...

**Comment by v1r0x** [comment]
@dartcafe Done! Thanks for your fixes!

**Comment by horstvogel** [comment]
I have still the Problem, on Nextlcloud 15.05 with polls 0.10.1, even after a complet Restart of the system

**Comment by gschbro** [comment]
Confirmed, same here NC 15.0.5 Polls 0.10.1 :-(

**Comment by dieter-wilhelm** [comment]
The same here on Nextlcloud 15.05 with polls 0.10.1, I even had to clear my FF cache to see the old polls.  But still not able to share old and new polls.

**Comment by dartcafe** [comment]
@v1r0x I had an issue with the build system on debian. Could you please make an `npm install` and `npm update` and run the build again. I can reproduce this issue but didn`t have it after updating the buld system.

Strange, I believed, npm would handle it by itself on `npm install`.

**Comment by dartcafe** [comment]
Just for clarification:
* my windows build worked fine
* with my debian build (make all) I could reproduce the problem in the package.
* updating npm fixed the problem and the debian build was ok

**Comment by andriusign** [comment]
Confirm, same error. Nextcloud 15.0.5, 
![error](https://user-images.githubusercontent.com/14263959/54084505-28039b80-433a-11e9-81af-2f33cd29f797.jpg)
Polls 0.10.1 (fixed poll expiration, broke poll sharing). LOL.
When the fix gonna be available? Need voting today and it broke. :(

**Comment by v1r0x** [comment]
You can try #542 and build the app yourself. I tried to test it, but CSP blocked it. Might work for you.

**Comment by andriusign** [comment]
Thanks a lot. Will try.
