### ISSUE TITLE
[1.0-beta3] Add error handling for contacts

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#726]
Also I have a problem when I try to add some recipient:
```
[PHP] Error: Undefined index: ORG at /var/www/nextcloud/apps/polls/lib/Controller/SystemController.php#168 POST /index.php/apps/polls/siteusers/get/
from 192.168.0.254 by olivier at 2020-01-10T19:05:18+00:00

[PHP] Error: Undefined index: PHOTO at /var/www/nextcloud/apps/polls/lib/Controller/SystemController.php#174 POST /index.php/apps/polls/siteusers/get/
from 192.168.0.254 by olivier at 2020-01-10T19:05:18+00:00

[PHP] Error: Undefined index: userEmail at /var/www/nextcloud/apps/polls/lib/Controller/ShareController.php#156 POST /index.php/apps/polls/share/write/
from 192.168.0.254 by olivier at 2020-01-10T19:30:07+00:00
```
And I have the same kind of error when I try to create a public link...
and I can't share the poll with anybody...

_Originally posted by @leolivier in https://github.com/nextcloud/polls/issues/706#issuecomment-573174356_

**Comment by Findus23** [comment]
I am still getting `Undefined index: userEmail` when pulically sharing a poll with the stable release.

**Comment by Dennis1993** [comment]
I've the same problem too. We cant use this app...
Please fix it and create a new release to make this app useable.
Thanks!

Nextcloud 18 (fresh installation) on Ubuntu 18 with PHP 7.2

Error if I share my poll:

> Undefined index: userEmail at /var/www/html/apps/polls/lib/Controller/ShareController.php#156

**Comment by bloodhunterd** [comment]
First of all - great app - but same problem here, if I try to share with users, contacts or create a public link:

> Undefined index: userEmail at /var/www/html/custom_apps/polls/lib/Controller/ShareController.php#156

- Nextcloud 17.0.2 (stable)
- PHP 7.3
- App version 1.0.0.

Would be great, if this will be fixed fast. Thanks!

**Comment by dartcafe** [comment]
Is fixed, but release is pending. Stay tuned for Version 1.1.
I will publish a pre-release this evening for manual install.

**Comment by dartcafe** [comment]
You can try the pre-release. Appstore release will be the same with updated versio number. 
https://github.com/nextcloud/polls/releases/download/v1.1.0-rc/polls-1.1.0.RC.zip

**Comment by dartcafe** [comment]
Please give feedback, if this works now.

**Comment by Findus23** [comment]
I think I am doing something wrong as I manually applied https://github.com/nextcloud/polls/commit/84e4f8b78085c04378e2a26b912a1a824db2c9cf. Now there is no more error in the PHP or Nextcloud log.
But I still can't pulically share a poll the request still returns a 409 Conflict.
POST parameters are `{"pollId":14,"share":{"type":"public","userId":"","pollId":14,"token":""}}`, response is `{}`

**Comment by Findus23** [comment]
In case it helps: I removed the catch below:
https://github.com/nextcloud/polls/blob/84e4f8b78085c04378e2a26b912a1a824db2c9cf/lib/Controller/ShareController.php#L173-L175

And now this error popped up in my Sentry instance:

An exception occurred while executing 'INSERT INTO `oc_polls_share` (`type`, `poll_id`, `user_id`, `user_email`, `token`) VALUES(?, ?, ?, ?, ?)' with params ["public", 14, "", "", "GN4e1WT24Rm1kRjP"]:

SQLSTATE[HY000]: General error: 1364 Field 'user' doesn't have a default value

**Comment by dartcafe** [comment]
Seems I messed up some things. Will fix it after some reviews. Update will come tonight.

**Comment by Findus23** [comment]
In case it helps: This is my database.
![grafik](https://user-images.githubusercontent.com/6266037/72937951-59c2fc80-3d6a-11ea-8e87-5b8ecd132299.png)

**Comment by dartcafe** [comment]
Strange, that user defaults to null. The migration says default = ''. 
But the column seems to be filled with ''

**Comment by SystemKeeper** [comment]
> But the column seems to be filled with ''
Guess that's because "null" is not allowed for user ("Null" -> "NO").

**Comment by Dennis1993** [comment]
We use NextCloud with LDAP. The Usernames are like S-1-63737283873-7374838-83747 and not the name of a user like „John Doe“ e.g.
Maybe that is a problem? In all other apps the names are correct loaded 🙂

**Comment by RainerEmrich** [comment]
We should use the users "display name" where possible not the "username".

**Comment by dartcafe** [comment]
Seemd to be related to #771 
@Dennis1993 @RainerEmrich see #715

**Comment by dartcafe** [comment]
Symtoms were the same as in #771. Should be finally fixed with #778
